[database]
# host, port, etc
# for a full list of keys usable here,
# see https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect
database = 'ec'

[tokens]
discord = 'Mz...'

[support_server]
id = 1234
moderator_role_id = 5678
