[database]
# host, port, etc
# for a full list of keys usable here,
# see https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect
database = 'ec'

[tokens]
discord = 'NzA3NzYyNjQxMTk5ODI0ODk3.XrNhXA.ji48Vkqb0yIZJ_97Arn_PAqewOk'

[support_server]
id = 410627685589450752
moderator_role_id = 451282186872553472
